### PR TITLE
Add CI/CD pipeline

### PR DESCRIPTION
**Pull request by ctyar**
The only thing that remains is adding the secrets to the repo which I'm waiting for access from @paulchrisluke

### CODE REVIEW

**Comment by ctyar** [comment]
@giteshk11 If it's fine with you we should merge this

**Comment by giteshk11** [comment]
@ctyar db will be Postgres right?

**Comment by ctyar** [comment]
Yes

**Comment by giteshk11** [comment]
Then we can merge it

**Pull request merged**
